color: orange
fieldLayouts:
  4d5b743b-fda2-435a-9033-27e958fe190b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: 'List of Faculty Programs will be inserted here.'
            dateAdded: '2025-04-24T02:47:54+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: 5962d7a3-53b8-4813-8fdc-95d9e9472c86
            userCondition: null
            width: 100
        name: Content
        uid: 0201e9e9-067d-4069-9932-2a580008a352
        userCondition: null
handle: blockFacultyPrograms
hasTitleField: false
icon: scroll
name: 'Block: Faculty Programs'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
