color: orange
fieldLayouts:
  1da4fe64-453f-4593-8de7-cb2b9df82de5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: 'Programme structure will be inserted here.'
            dateAdded: '2025-04-25T04:19:42+00:00'
            displayInPane: false
            elementCondition: null
            type: craft\fieldlayoutelements\Markdown
            uid: e17f6413-35da-4444-8225-0319b5d4ba48
            userCondition: null
            width: 100
        name: Content
        uid: 0581016a-1dd0-4148-9c53-51c2f4de1715
        userCondition: null
handle: block_programmeStructure
hasTitleField: false
icon: scroll
name: 'Block: Programme Structure'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
