color: null
fieldLayouts:
  5333638f-9ef5-4fd0-91dc-aa91e481cdef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-28T02:49:06+00:00'
            elementCondition: null
            fieldUid: 2bfee73d-1d4f-480f-9a78-6be8410a6704 # Social Media
            handle: null
            includeInCards: false
            instructions: null
            label: Type
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 742d885a-59ff-4bb3-9859-0e55b20f841a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-02-28T02:49:06+00:00'
            elementCondition: null
            fieldUid: b5e4cb0a-59d9-4e16-bfc3-408104521a11 # URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bbccace9-a779-46a5-a140-122be81e4f35
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: e4177286-0795-4c65-9c41-4160a793283c
        userCondition: null
handle: contactSocialMedia
hasTitleField: false
icon: link
name: 'Social Media'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
