allowLineBreaksInTitles: false
color: blue
description: null
fieldLayouts:
  fb061e68-5c10-415a-990a-2755ab14800a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-08T12:13:30+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b5e4cb0a-59d9-4e16-bfc3-408104521a11 # URL
            handle: hyperlink
            instructions: null
            label: __blank__
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 764aa847-dcb8-45ca-8cfc-aa326650b45a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7ea333a8-9a98-48c8-9b97-40d5409e5346
        userCondition: null
    thumbFieldKey: null
handle: contactWebsite
hasTitleField: false
icon: globe
name: 'Contact: Website'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
