color: null
fieldLayouts:
  8cd5c1df-6543-409c-905e-8eade25d5170:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-25T07:54:22+00:00'
            elementCondition: null
            fieldUid: b5e4cb0a-59d9-4e16-bfc3-408104521a11 # URL
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a95611d1-3fe4-47e1-931b-5264f6ddd545
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 55bd4602-510d-410b-8fdf-87a33ab2f779
        userCondition: null
handle: contactWebsite
hasTitleField: false
icon: up-right-from-square
name: 'Contact: Website'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
