allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  c11a1cf3-0842-4d08-af82-b61c2aae0ec4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-09T07:11:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1d4a1588-fa06-4bb8-acb9-7df7cc03543d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T10:50:20+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8dddc601-5e96-40bb-b036-520072ba4aa7 # Images
            handle: carousel
            instructions: null
            label: 'Banner Carousel'
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6872b371-7f08-4e8a-84a0-c83663902c40
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-24T03:13:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 386721be-1ee4-4e3b-b22c-7fb3dfded3ff # Simple Text
            handle: introduction
            instructions: null
            label: Introduction
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85bd832e-6f5d-409c-ad53-0188a52978e9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T10:50:20+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a9736c79-b219-4814-ba33-728835b7d230 # Body
            handle: null
            instructions: null
            label: Description
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcab25ee-edd1-489c-b0da-0f5489c30243
            userCondition: null
            warning: null
            width: 100
        name: Page
        uid: bd308d9b-4552-4b33-a434-c8592a1b8de4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-23T03:18:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: aab7a3de-9a4a-4020-97b0-d960292b931f # Content Blocks: Faculty
            handle: contentBlocks
            instructions: null
            label: 'Content Blocks'
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9811074a-cac0-4a4c-90f2-907043e230cc
            userCondition: null
            warning: null
            width: 100
        name: Blocks
        uid: 872d2788-25ab-4a2c-b92c-7eb13941d44c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-23T03:11:33+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 856911a9-89f9-4865-bdb1-5665460c6c23 # Contact & Social Media Information
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 949ae227-22b3-4d26-b260-aa15c66e2049
            userCondition: null
            warning: null
            width: 100
        name: Contact
        uid: af10e674-75e0-4b1a-ad46-0d5e25ae2ad9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-18T10:49:26+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5b72b712-0218-40c6-9717-0c395a914ad8 # Summary
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44f5e105-453a-4a8e-836b-6500c6208b08
            userCondition: null
            warning: null
            width: 100
        name: Summary
        uid: 3307934b-0793-4e34-a701-782424ede547
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-18T10:49:26+00:00'
            elementCondition: null
            template: _cp/instructions/seo.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: af090b2c-d007-427f-a14c-c2434a2b9053
            userCondition: null
            width: 100
          -
            dateAdded: '2025-04-18T10:49:26+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: da24c053-b31c-4fa8-b113-217845a4ce83 # Share/SEO Title
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34336193-afcf-42fc-bbca-38978dd5b82b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T10:49:26+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 349b5e6f-3a2a-43f1-a9dd-2373bf4a0a67 # Share/SEO Description
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bb71ae9-ba24-4585-91cb-3f350a7d86fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T10:49:26+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d4720a93-54ad-45de-a939-b668ed8660dc # Share/SEO Image
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e35961e-a324-45ab-b419-c3f177502c41
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T10:49:26+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: c1be94c2-9b25-458c-826b-bdf47c4b4a84
            userCondition: null
          -
            dateAdded: '2025-04-18T10:49:26+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 61317d04-b4b5-4b2f-ad77-e1d87029c361 # Legacy URL
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e3b87f8-7ed7-4cd7-af18-6c90f5c96b74
            userCondition: null
            warning: null
            width: 100
        name: 'Sharing & SEO'
        uid: e9113674-0bc9-4e80-aad7-578692af6164
        userCondition: null
    thumbFieldKey: null
handle: department
hasTitleField: true
icon: building
name: Department
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
