color: null
fieldLayouts:
  ccb6f9a2-b037-48d3-9dd8-333530aa8e65:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-26T02:29:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b8a3d948-a454-4787-a0bb-9680311de7ab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T02:53:40+00:00'
            elementCondition: null
            fieldUid: 9b5f9007-3f61-4857-b978-fdfbc4b29dba # Exhibition Types
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cc09c24-ea29-47ac-aa51-21495d792080
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-26T02:38:49+00:00'
            elementCondition: null
            fieldUid: 69339afc-d4f1-440b-a7ad-7da2ccb77972 # Image
            handle: cover
            includeInCards: false
            instructions: null
            label: 'Cover Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04ba682b-6348-48de-833f-c03c6dd10b6b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-26T02:38:49+00:00'
            elementCondition: null
            fieldUid: bb0a4a47-dcbd-41a8-9bbb-82341295f5ff # Date
            handle: startDate
            includeInCards: false
            instructions: null
            label: 'Start Date'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e30e5ed4-2a93-4299-927a-7993d8dc68b3
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-26T02:38:49+00:00'
            elementCondition: null
            fieldUid: bb0a4a47-dcbd-41a8-9bbb-82341295f5ff # Date
            handle: endDate
            includeInCards: false
            instructions: null
            label: 'End Date'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f13ccc6-9d8e-4cbb-b64c-7821ab39219b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-26T02:40:53+00:00'
            elementCondition: null
            fieldUid: afc7f0bc-1b97-4841-a1d2-5b0385a7ca35 # Plain Text
            handle: location
            includeInCards: false
            instructions: null
            label: Location
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4c78f42-c653-4f93-8661-742ba26442c5
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-26T02:38:49+00:00'
            elementCondition: null
            fieldUid: d356acc9-4ecf-488d-a89d-2857490bb576 # Hyperlink
            handle: registrationLink
            includeInCards: false
            instructions: null
            label: 'Registration Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56b8470c-c2ba-4889-8430-cae12cc6e7ef
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-26T02:38:49+00:00'
            elementCondition: null
            fieldUid: a9736c79-b219-4814-ba33-728835b7d230 # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 978cd301-6fd9-484e-adc8-f0453a0d541d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 75617204-c935-43b7-947d-d05cff433e07
        userCondition: null
handle: event
hasTitleField: true
icon: calendar-days
name: Event
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
