color: null
fieldLayouts:
  ef819201-f5c1-4e67-979f-65b3fd6eb9a1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-13T07:15:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 60f8a388-dd4f-46a4-870e-aea2e62eefa9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-13T07:21:09+00:00'
            elementCondition: null
            fieldUid: 69339afc-d4f1-440b-a7ad-7da2ccb77972 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: Portrait
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a81b4506-be42-4d2c-a721-aba2dfca7c19
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-13T07:21:09+00:00'
            elementCondition: null
            fieldUid: 856911a9-89f9-4865-bdb1-5665460c6c23 # Contact & Social Media Information
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56c2e9f4-1987-4064-947f-08a6935ab23f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-16T01:50:00+00:00'
            elementCondition: null
            fieldUid: 08b5b22b-fb98-46ef-8a90-e392edb2244f # Rich Text
            handle: bio
            includeInCards: false
            instructions: null
            label: Bio
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b36485c-18c7-4076-a451-819dbf338986
            userCondition: null
            warning: null
            width: 100
        name: Page
        uid: 00729573-9236-4b4b-ac77-3138b2cc63b5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-13T07:52:28+00:00'
            elementCondition: null
            fieldUid: 5b72b712-0218-40c6-9717-0c395a914ad8 # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1770d1a-a5e9-493b-a6ef-8529c2bf1053
            userCondition: null
            warning: null
            width: 100
        name: Summary
        uid: 77cdf692-294f-471d-9525-79f0fde80ca5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-13T07:52:28+00:00'
            elementCondition: null
            template: _cp/instructions/seo.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: 9b2d7617-aca1-47c0-8611-501b3d1c2fc3
            userCondition: null
            width: 100
          -
            dateAdded: '2025-04-13T07:52:28+00:00'
            elementCondition: null
            fieldUid: da24c053-b31c-4fa8-b113-217845a4ce83 # Share/SEO Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8c5f49b-9ae7-4b8d-9df4-e0775ce8210a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-13T07:52:28+00:00'
            elementCondition: null
            fieldUid: 349b5e6f-3a2a-43f1-a9dd-2373bf4a0a67 # Share/SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13a154a8-6113-4e25-9c4c-39e673515a10
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-13T07:52:28+00:00'
            elementCondition: null
            fieldUid: d4720a93-54ad-45de-a939-b668ed8660dc # Share/SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b1bd1de-3e9f-49f4-9106-a0df40ba021a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-13T07:52:28+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0a316be6-ef06-45b2-97fe-f1632051d73d
            userCondition: null
          -
            dateAdded: '2025-04-13T07:52:28+00:00'
            elementCondition: null
            fieldUid: 61317d04-b4b5-4b2f-ad77-e1d87029c361 # Legacy URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a31d5835-55ca-4d04-a986-223a2eb91cdd
            userCondition: null
            warning: null
            width: 100
        name: 'Sharing & SEO'
        uid: 0b8b9169-bf5b-416d-8cce-6770df63ea80
        userCondition: null
handle: externalContributor
hasTitleField: true
icon: handshake
name: 'External Contributor'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
