allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  ef819201-f5c1-4e67-979f-65b3fd6eb9a1:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-13T07:15:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 60f8a388-dd4f-46a4-870e-aea2e62eefa9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-16T02:04:18+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 840acb32-6694-40d0-9384-60a0220c1de0 # Label
            handle: designation
            instructions: null
            label: Designation
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d1d62ec-a0bd-402d-806b-ecef2485ba05
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-13T07:21:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 69339afc-d4f1-440b-a7ad-7da2ccb77972 # Image
            handle: null
            instructions: null
            label: Portrait
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a81b4506-be42-4d2c-a721-aba2dfca7c19
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-16T01:50:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 08b5b22b-fb98-46ef-8a90-e392edb2244f # Rich Text
            handle: bio
            instructions: null
            label: Bio
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b36485c-18c7-4076-a451-819dbf338986
            userCondition: null
            warning: null
            width: 100
        name: Profile
        uid: 00729573-9236-4b4b-ac77-3138b2cc63b5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-22T07:47:34+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9cbdb5d5-1a67-4b57-820f-7226cef3d0c8 # External Person Roles
            handle: roles
            instructions: null
            label: Roles
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4fa8150e-2258-4471-91e3-218f423c715d
            userCondition: null
            warning: null
            width: 100
        name: Roles
        uid: 9dbd1acf-5751-4881-a52f-55620cd78c03
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-13T07:21:09+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 856911a9-89f9-4865-bdb1-5665460c6c23 # Contact & Social Media Information
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56c2e9f4-1987-4064-947f-08a6935ab23f
            userCondition: null
            warning: null
            width: 100
        name: Contact
        uid: 6f98b81c-b0df-41c2-8d1d-66f494898307
        userCondition: null
      -
        elementCondition:
          class: craft\elements\conditions\entries\EntryCondition
          conditionRules:
            -
              class: craft\fields\conditions\OptionsFieldConditionRule
              fieldUid: 9cbdb5d5-1a67-4b57-820f-7226cef3d0c8 # External Person Roles
              layoutElementUid: 4fa8150e-2258-4471-91e3-218f423c715d
              operator: in
              uid: 3ac00040-2a6c-4c7e-b126-04702a8d2043
              values:
                - guestWithProfile
          elementType: craft\elements\Entry
          fieldContext: global
        elements:
          -
            dateAdded: '2025-04-23T02:56:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5b72b712-0218-40c6-9717-0c395a914ad8 # Summary
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8c68515a-f7ca-4455-b20b-f5bf1351a189
            userCondition: null
            warning: null
            width: 100
        name: Summary
        uid: 948e7509-1667-4502-add7-f272f8d1c63c
        userCondition: null
      -
        elementCondition:
          class: craft\elements\conditions\entries\EntryCondition
          conditionRules:
            -
              class: craft\fields\conditions\OptionsFieldConditionRule
              fieldUid: 9cbdb5d5-1a67-4b57-820f-7226cef3d0c8 # External Person Roles
              layoutElementUid: 4fa8150e-2258-4471-91e3-218f423c715d
              operator: in
              uid: 89997885-8c59-426b-8ce9-ede4686b7c41
              values:
                - guestWithProfile
          elementType: craft\elements\Entry
          fieldContext: global
        elements:
          -
            dateAdded: '2025-04-23T02:58:24+00:00'
            elementCondition: null
            template: _cp/instructions/seo.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: cdd4e514-974d-4ca8-b6e7-e08c9eadcb11
            userCondition: null
            width: 100
          -
            dateAdded: '2025-04-23T02:58:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: da24c053-b31c-4fa8-b113-217845a4ce83 # Share/SEO Title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 152efffe-371c-40a1-afba-976529a1cbe5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T02:58:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 349b5e6f-3a2a-43f1-a9dd-2373bf4a0a67 # Share/SEO Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e815dc1-cdd8-49cc-b74a-4486f259cec6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T02:58:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d4720a93-54ad-45de-a939-b668ed8660dc # Share/SEO Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29334484-ee65-45fd-84bd-10e1247762d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-23T02:58:24+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 6171adcb-a5e4-4213-855f-64ffe99b9847
            userCondition: null
          -
            dateAdded: '2025-04-23T02:58:24+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 61317d04-b4b5-4b2f-ad77-e1d87029c361 # Legacy URL
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: defc9ca9-f12c-45f8-8f8c-a68950ba07aa
            userCondition: null
            warning: null
            width: 100
        name: 'Sharing & SEO'
        uid: d72af6ca-5d37-45b1-98de-4cf02d616ce8
        userCondition: null
    thumbFieldKey: null
handle: externalPerson
hasTitleField: true
icon: handshake
name: 'People: External Contributor'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
