color: emerald
description: null
fieldLayouts:
  d57dc989-026e-44e3-90df-3338cb9510c1:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:3902ac3c-675a-4aa2-ac86-195a608ca6f0'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-28T13:11:46+00:00'
            elementCondition: null
            template: _cp/instructions/blockHeading.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: 4cbfccec-9e7b-4f35-886f-ff467986c0e8
            userCondition: null
            width: 100
          -
            dateAdded: '2024-12-17T21:53:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69339afc-d4f1-440b-a7ad-7da2ccb77972 # Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: 'Double-click the image to add “alt” text for visually impaired users.'
            type: craft\fieldlayoutelements\CustomField
            uid: 2ca1af80-1f48-4a75-a5f0-3f982c05c447
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T21:53:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 386721be-1ee4-4e3b-b22c-7fb3dfded3ff # Simple Text
            handle: caption
            instructions: null
            label: Caption
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3902ac3c-675a-4aa2-ac86-195a608ca6f0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 423b9365-d39f-4522-9b01-20fd9726fbc3
        userCondition: null
    thumbFieldKey: 'layoutElement:2ca1af80-1f48-4a75-a5f0-3f982c05c447'
handle: image
hasTitleField: false
icon: image
name: Image
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
