allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  d30fb484-d5e7-44d6-ae65-f8924f1c1012:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-07T23:01:57+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 840acb32-6694-40d0-9384-60a0220c1de0 # Label
            handle: headline
            instructions: null
            label: Headline
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60727df4-4e97-4929-b920-8fb343402f9e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-09-07T23:01:57+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 386721be-1ee4-4e3b-b22c-7fb3dfded3ff # Simple Text
            handle: introduction
            instructions: null
            label: Introduction
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98cce6ea-9657-4941-b892-f064ad435103
            userCondition: null
            warning: null
            width: 100
        name: Page
        uid: 4c017ef0-a804-4f0f-aa5f-8f8ba028442a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-09-07T23:03:26+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 840acb32-6694-40d0-9384-60a0220c1de0 # Label
            handle: null
            instructions: null
            label: Title
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85d2e2b2-ee47-4b67-b601-836a464aa190
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: 6d037a17-526f-4ee0-be3b-46128fef5874
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-17T21:42:49+00:00'
            elementCondition: null
            template: _cp/instructions/seo
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: 9dc9b553-7ba7-4818-9840-6b33ca82043a
            userCondition: null
            width: 100
          -
            dateAdded: '2024-12-17T21:42:49+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: da24c053-b31c-4fa8-b113-217845a4ce83 # Share/SEO Title
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e14ca843-194f-4f0a-bcaf-00473fa52083
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T21:42:49+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 349b5e6f-3a2a-43f1-a9dd-2373bf4a0a67 # Share/SEO Description
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36b55424-f42a-481e-8e9c-0a54120ab0a7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T21:42:49+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d4720a93-54ad-45de-a939-b668ed8660dc # Share/SEO Image
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c7da19b-6080-4fc4-b208-6d49bed23dde
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T21:42:49+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 9d78f0ac-8c10-41db-92d3-a19c5bdaf36e
            userCondition: null
          -
            dateAdded: '2024-12-17T21:42:49+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 61317d04-b4b5-4b2f-ad77-e1d87029c361 # Legacy URL
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e14c4ca-0678-421d-afac-741673988914
            userCondition: null
            warning: null
            width: 100
        name: 'Sharing & SEO'
        uid: 028bf537-803c-4ad5-8b5a-134e61ecca3f
        userCondition: null
    thumbFieldKey: null
handle: index
hasTitleField: false
icon: list-tree
name: 'Index Page'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: "{% include '_generated/index/title' %}"
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{section.name}'
