color: null
fieldLayouts:
  e7a92393-9608-4ef8-8b61-26cd9344c101:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-13T07:01:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 08b84705-7e78-4b86-b855-b59a0e9ff9b9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-13T07:06:54+00:00'
            elementCondition: null
            fieldUid: 69339afc-d4f1-440b-a7ad-7da2ccb77972 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc1be8c8-5998-4107-a7cc-5dfa91a2e834
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-13T07:06:54+00:00'
            elementCondition: null
            fieldUid: 856911a9-89f9-4865-bdb1-5665460c6c23 # Contact & Social Media Information
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dacc502d-89a5-443a-8acd-d8f413cf50b2
            userCondition: null
            warning: null
            width: 100
        name: Page
        uid: f052a411-0c92-4669-bf4a-8f9d613feac0
        userCondition: null
handle: member
hasTitleField: true
icon: user
name: Member
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
