color: null
description: null
fieldLayouts:
  d3c9d268-7563-4f26-aca6-837870e22708:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-24T11:01:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c16e920d-e7e5-4510-8dde-4f1b5627b97f # Link (Entries, URL)
            handle: hyperlink
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ffeec11-ac9a-4641-b2d5-09d04c31dcb2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a5036032-55f3-454f-bbbc-d52c5693cef6
        userCondition: null
handle: navLink_entriesUrl
hasTitleField: false
icon: link
name: 'Navigation Link'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
