color: null
fieldLayouts:
  e7a92393-9608-4ef8-8b61-26cd9344c101:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-13T07:01:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 08b84705-7e78-4b86-b855-b59a0e9ff9b9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-16T02:04:45+00:00'
            elementCondition: null
            fieldUid: 840acb32-6694-40d0-9384-60a0220c1de0 # Label
            handle: designation
            includeInCards: false
            instructions: null
            label: Designation
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2cc78395-40af-417a-a4ad-49a225764985
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-13T07:06:54+00:00'
            elementCondition: null
            fieldUid: 69339afc-d4f1-440b-a7ad-7da2ccb77972 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: Portrait
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc1be8c8-5998-4107-a7cc-5dfa91a2e834
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-13T07:55:25+00:00'
            elementCondition: null
            fieldUid: 08b5b22b-fb98-46ef-8a90-e392edb2244f # Rich Text
            handle: bio
            includeInCards: false
            instructions: null
            label: Bio
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a9c194b-b354-4ec1-9179-45a61899c81e
            userCondition: null
            warning: null
            width: 100
        name: Profile
        uid: f052a411-0c92-4669-bf4a-8f9d613feac0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-17T05:02:53+00:00'
            elementCondition: null
            fieldUid: 8f58365f-4eeb-4347-9d3d-5c0d3ffd3989 # Toggle (Default: off)
            handle: isAlumni
            includeInCards: false
            instructions: 'Alumni will not get a public page.'
            label: 'Is Alumni?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9644274f-ad63-4409-9003-7ab68e1eaaf4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-17T04:38:10+00:00'
            elementCondition: null
            fieldUid: 11127416-2baf-40e9-bb28-9ea76040af2a # Person Roles
            handle: roles
            includeInCards: false
            instructions: 'People with only an _Ambassador_ role will not get a public page.'
            label: Roles
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 180d4fc7-9ed8-45dd-8658-851b8d3687ea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T04:09:13+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 11127416-2baf-40e9-bb28-9ea76040af2a # Person Roles
                  layoutElementUid: 180d4fc7-9ed8-45dd-8658-851b8d3687ea
                  operator: in
                  uid: 026a29b8-c3a9-47de-bc26-7b8c7046dbdf
                  values:
                    - faculty
                    - student
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 86d5863c-5339-40bb-9add-f4872cdfdce5 # Departments
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 210f744d-d380-4b33-8c71-efee8432c558
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T04:22:14+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 11127416-2baf-40e9-bb28-9ea76040af2a # Person Roles
                  layoutElementUid: 180d4fc7-9ed8-45dd-8658-851b8d3687ea
                  operator: in
                  uid: e394b6e5-5a5b-4b34-9dbf-a4976090b9c1
                  values:
                    - staff
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 16ca56d3-1df0-41ad-9bf1-f0b273739be2 # Offices
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2658265c-3e39-472c-9619-27093888b943
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T04:09:13+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 11127416-2baf-40e9-bb28-9ea76040af2a # Person Roles
                  layoutElementUid: 180d4fc7-9ed8-45dd-8658-851b8d3687ea
                  operator: in
                  uid: 066d91e9-48f8-41dc-9aae-42e2c8b02898
                  values:
                    - faculty
                    - student
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: b41f3521-c73f-45d7-baac-db7ec5a54bd1 # Programmes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 430e5bb8-7c59-4d2e-a3bf-a0ebe904a284
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T04:09:13+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 11127416-2baf-40e9-bb28-9ea76040af2a # Person Roles
                  layoutElementUid: 180d4fc7-9ed8-45dd-8658-851b8d3687ea
                  operator: in
                  uid: eeafe1af-9a3d-44e8-b445-1874efa0546d
                  values:
                    - faculty
                    - staff
                    - student
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 9ce8d4e8-4f27-44a1-8f1c-60187033a3e3 # Focus Areas
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3188eeb4-372a-4b9e-a4a4-50345d3712c5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-18T04:09:13+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 11127416-2baf-40e9-bb28-9ea76040af2a # Person Roles
                  layoutElementUid: 180d4fc7-9ed8-45dd-8658-851b8d3687ea
                  operator: in
                  uid: 092d7dd8-e61f-4f63-9211-70c7a0277cac
                  values:
                    - faculty
                    - student
                    - staff
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: a0320c92-dcb7-489b-94e3-bd21fdc647cc # Practices
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 814b97f8-8873-4e51-86c5-f372b7073dff
            userCondition: null
            warning: null
            width: 100
        name: Roles
        uid: 52c1bed4-7ef0-4add-82b4-099fa3efabf0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-13T07:06:54+00:00'
            elementCondition: null
            fieldUid: 856911a9-89f9-4865-bdb1-5665460c6c23 # Contact & Social Media Information
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dacc502d-89a5-443a-8acd-d8f413cf50b2
            userCondition: null
            warning: null
            width: 100
        name: Contact
        uid: 27ae856c-8d21-40f0-a53c-1283b40db426
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-13T07:50:34+00:00'
            elementCondition: null
            fieldUid: 5b72b712-0218-40c6-9717-0c395a914ad8 # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4eeefbc0-dbf7-4150-bf89-78106a6a0d31
            userCondition: null
            warning: null
            width: 100
        name: Summary
        uid: 759f924d-7e40-427c-9ab6-2988bcc89081
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-13T07:50:34+00:00'
            elementCondition: null
            template: _cp/instructions/seo.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: b333acec-873b-4ea8-aa17-643e9f167248
            userCondition: null
            width: 100
          -
            dateAdded: '2025-04-13T07:50:34+00:00'
            elementCondition: null
            fieldUid: da24c053-b31c-4fa8-b113-217845a4ce83 # Share/SEO Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d7712f3-d44b-46b9-a5ae-dbafc3c920c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-13T07:50:34+00:00'
            elementCondition: null
            fieldUid: 349b5e6f-3a2a-43f1-a9dd-2373bf4a0a67 # Share/SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 246b03f9-4545-47f4-877c-37db34c7e01e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-13T07:50:34+00:00'
            elementCondition: null
            fieldUid: d4720a93-54ad-45de-a939-b668ed8660dc # Share/SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4f2a0c1-baad-4e1a-b8e2-ebf60077de7b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-13T07:50:34+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: e1d7dfd5-7634-46d1-8cb2-48ee052ba632
            userCondition: null
          -
            dateAdded: '2025-04-13T07:50:34+00:00'
            elementCondition: null
            fieldUid: 61317d04-b4b5-4b2f-ad77-e1d87029c361 # Legacy URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 953d6d07-c2a5-4956-8e22-0910b8bece9c
            userCondition: null
            warning: null
            width: 100
        name: 'Sharing & SEO'
        uid: b311276a-8b36-479e-a3f6-58f18ce32398
        userCondition: null
handle: orgPerson
hasTitleField: true
icon: user
name: 'Org Member'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
