color: null
fieldLayouts:
  97ecd586-0185-45f2-b54d-bb0ec8973c8f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-08T10:40:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5fd79acf-3e13-4108-b3e4-d5a0c7a36a30
            userCondition: null
            warning: null
            width: 100
        name: Page
        uid: 5c90ee96-a7ac-4922-9fa8-df2639aeb188
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-08T10:44:07+00:00'
            elementCondition: null
            fieldUid: 5b72b712-0218-40c6-9717-0c395a914ad8 # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0f56691-76cd-455f-a9e6-260c532ba933
            userCondition: null
            warning: null
            width: 100
        name: Summary
        uid: 551864ba-41f0-410d-8f21-b820987f02de
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-08T10:44:07+00:00'
            elementCondition: null
            template: _cp/instructions/seo.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: 2c3c1528-bf78-496e-810a-2c732fe7f55f
            userCondition: null
            width: 100
          -
            dateAdded: '2025-04-08T10:44:07+00:00'
            elementCondition: null
            fieldUid: da24c053-b31c-4fa8-b113-217845a4ce83 # Share/SEO Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ccaaf3f-6f14-47ba-a46b-09f04746ef32
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-08T10:44:07+00:00'
            elementCondition: null
            fieldUid: 349b5e6f-3a2a-43f1-a9dd-2373bf4a0a67 # Share/SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d8c4e0d-3bac-46a8-956a-ec0ed75a5086
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-08T10:44:07+00:00'
            elementCondition: null
            fieldUid: d4720a93-54ad-45de-a939-b668ed8660dc # Share/SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbf358d3-81c5-4d2a-be25-0f2e84be46e7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-08T10:44:07+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 45e1d70a-cd35-4f2e-8075-98d2a6a6d35f
            userCondition: null
          -
            dateAdded: '2025-04-08T10:44:07+00:00'
            elementCondition: null
            fieldUid: 61317d04-b4b5-4b2f-ad77-e1d87029c361 # Legacy URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d6484b4-c40a-4eeb-9005-a5d91df573a2
            userCondition: null
            warning: null
            width: 100
        name: 'SEO / Sharing'
        uid: 1b4f6c72-258d-4044-a3e2-7f8fa22fc26e
        userCondition: null
handle: program
hasTitleField: true
icon: graduation-cap
name: Program
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
