color: null
description: null
fieldLayouts:
  2f57518d-0729-49ef-952b-e5f7274afe6d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-29T07:16:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9cdbe130-8215-4820-9e0a-a730907991d5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T10:37:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69339afc-d4f1-440b-a7ad-7da2ccb77972 # Image
            handle: cover
            instructions: null
            label: Cover
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c23235ee-4519-43fe-b161-c4bce5b1b5c1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T07:26:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 08b5b22b-fb98-46ef-8a90-e392edb2244f # Rich Text
            handle: introduction
            instructions: null
            label: Introduction
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cdc72378-d354-4752-974b-5f43890d70b4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T07:26:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a9736c79-b219-4814-ba33-728835b7d230 # Body
            handle: null
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e286669f-40c0-42ba-90cd-941b5edebf1e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 338a9d79-a779-48d0-8418-d76d8e426ef4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-29T07:54:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 358a570b-6122-4744-9b73-575c44b2f9df # Content Blocks: Projects
            handle: contentBlocks
            instructions: null
            label: 'Content Blocks'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67b36041-bb74-498a-b561-1ee85dd6af46
            userCondition: null
            warning: null
            width: 100
        name: Blocks
        uid: 66eb5b22-c531-45d6-b05e-2e7ca5077e6f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-29T10:29:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e4da781-e103-48f1-a607-5396f2be279e # Project Types
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0ffe5a4-682f-4ef6-b7b3-96906d195e1d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T10:32:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 840acb32-6694-40d0-9384-60a0220c1de0 # Label
            handle: periodPublishedStr
            instructions: null
            label: 'Year Published'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34aa89a8-32c1-403a-bae4-9df8bf011d91
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T10:05:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9f26c9a-936a-4901-90ca-e8c5c2997475 # Teams
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc26ce4c-37b7-40db-97ad-368c9136952e
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: c2389e79-7f4d-462a-a586-fa0b0a35f06b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-29T10:26:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 86d5863c-5339-40bb-9add-f4872cdfdce5 # Departments
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e75794da-478f-461d-b839-b0c7aab15ed2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T10:32:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 16ca56d3-1df0-41ad-9bf1-f0b273739be2 # Offices
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bbb77e2-bb7f-45c3-ad81-9da2f229ca46
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-01T02:17:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a60b8050-4e83-40d0-9598-4a9572ce027a # Location
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de438f06-818a-4c9e-bec4-10f02f7954fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T10:26:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b41f3521-c73f-45d7-baac-db7ec5a54bd1 # Programmes
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66b6e209-4352-41ca-85a5-030cd0a45423
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T10:32:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a0320c92-dcb7-489b-94e3-bd21fdc647cc # Practices
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d403b794-9764-4c0e-870b-b38cfac361eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T10:32:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69dcd3aa-18b8-48bf-a7d3-deb9c6912349 # Topics
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3c60567-17bd-4406-9726-1eac3d7510fb
            userCondition: null
            warning: null
            width: 100
        name: Related
        uid: 117ff8dd-0514-4498-af32-fdfa68726684
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-29T07:23:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5b72b712-0218-40c6-9717-0c395a914ad8 # Summary
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdb2a2da-7d11-41bb-97b6-8df86e6731ed
            userCondition: null
            warning: null
            width: 100
        name: Summary
        uid: c15e1ef7-6da3-4994-a9f1-fe60b8f62b71
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-29T07:23:07+00:00'
            elementCondition: null
            template: _cp/instructions/seo.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: 51d1ce45-2614-4be7-9b96-131ab4b2da73
            userCondition: null
            width: 100
          -
            dateAdded: '2025-04-29T07:23:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da24c053-b31c-4fa8-b113-217845a4ce83 # Share/SEO Title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc907190-4a33-48c8-b95a-8ee0ed77e43f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T07:23:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 349b5e6f-3a2a-43f1-a9dd-2373bf4a0a67 # Share/SEO Description
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9386e15-9f34-4830-922a-e2eee81f810a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T07:23:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d4720a93-54ad-45de-a939-b668ed8660dc # Share/SEO Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0d4f315-c49f-49f2-9fb4-cf14b31f5514
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-29T07:23:07+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 6137c884-b46c-4703-b8dc-85a678ab2525
            userCondition: null
          -
            dateAdded: '2025-04-29T07:23:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 61317d04-b4b5-4b2f-ad77-e1d87029c361 # Legacy URL
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c3d9a85-d2c6-4ff6-a748-5c8da642b660
            userCondition: null
            warning: null
            width: 100
        name: 'Sharing & SEO'
        uid: 5bd42340-d86b-49d7-91a2-985b9f7c2591
        userCondition: null
handle: project
hasTitleField: true
icon: brush
name: Project
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
