color: null
fieldLayouts:
  227e9d26-0f8f-44ef-b668-c439eff5df46:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-27T04:32:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b3fabcf7-360b-455c-8563-c85ab83e64bb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-28T08:54:00+00:00'
            elementCondition: null
            fieldUid: 69339afc-d4f1-440b-a7ad-7da2ccb77972 # Image
            handle: cover
            includeInCards: false
            instructions: null
            label: 'Cover Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e08372c-a233-407f-8e58-9e3782a8612b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T07:24:28+00:00'
            elementCondition: null
            fieldUid: 1a28c01c-3fa0-4a60-8c73-d7c7707be626 # Document
            handle: null
            includeInCards: false
            instructions: 'Optionally make a document available for download.'
            label: null
            providesThumbs: false
            required: false
            tip: 'Using the _Body_ field below for resource content will make it accessible to more devices and technologies.'
            type: craft\fieldlayoutelements\CustomField
            uid: 76160498-ef32-49bf-b1db-f5dd0f753621
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-28T08:54:00+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  fieldUid: 1a28c01c-3fa0-4a60-8c73-d7c7707be626 # Document
                  layoutElementUid: 76160498-ef32-49bf-b1db-f5dd0f753621
                  operator: notempty
                  uid: c6aa6fc0-7ffe-4d4e-8ea4-672027186323
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 32ed2f1a-9024-4ee9-9028-3a5041c0e5e6 # Date
            handle: null
            includeInCards: false
            instructions: null
            label: 'Date Updated'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9976c4e-75b9-4b12-bc2d-5f9e8cf8ca6e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-02-27T04:41:51+00:00'
            elementCondition: null
            fieldUid: a9736c79-b219-4814-ba33-728835b7d230 # Body
            handle: null
            includeInCards: false
            instructions: null
            label: Body
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43e8a921-2b66-4b33-84a4-8e8999f5c789
            userCondition: null
            warning: null
            width: 100
        name: Page
        uid: 8ff94327-55d3-4051-b60b-5469f5f6f537
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-27T04:42:27+00:00'
            elementCondition: null
            fieldUid: 1ba3b532-e3ed-43db-93a6-00c05efcc84f # Resource Types
            handle: null
            includeInCards: false
            instructions: null
            label: Types
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f68c0646-ce1d-493b-b1bf-676e45dafa2e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-28T08:54:00+00:00'
            elementCondition: null
            fieldUid: 69dcd3aa-18b8-48bf-a7d3-deb9c6912349 # Topics
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e82552a-2d31-4fc5-9a34-8786c428158c
            userCondition: null
            warning: null
            width: 100
        name: Related
        uid: 0804600b-7a8c-438a-b877-6a0c13f3435e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-27T04:41:37+00:00'
            elementCondition: null
            fieldUid: 5b72b712-0218-40c6-9717-0c395a914ad8 # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 35c20dd0-5dd1-4c30-82f6-dd05fdabdf2d
            userCondition: null
            warning: null
            width: 100
        name: Summary
        uid: 5d54fe93-8b69-4981-9aa6-d8758f8ca220
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-27T04:41:37+00:00'
            elementCondition: null
            template: _cp/instructions/seo.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: f02e0dad-6c08-4bd4-a5e7-7a658c64ca86
            userCondition: null
            width: 100
          -
            dateAdded: '2025-02-27T04:41:37+00:00'
            elementCondition: null
            fieldUid: da24c053-b31c-4fa8-b113-217845a4ce83 # Share/SEO Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90321148-3ad3-4dad-872e-e8722e555f6f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T04:41:37+00:00'
            elementCondition: null
            fieldUid: 349b5e6f-3a2a-43f1-a9dd-2373bf4a0a67 # Share/SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3a424d2-3a28-47a1-941b-2edff511f629
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T04:41:37+00:00'
            elementCondition: null
            fieldUid: d4720a93-54ad-45de-a939-b668ed8660dc # Share/SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 402a7f6e-067c-45cc-8e49-a363686fd4d4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-27T04:41:37+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 79450816-5172-4318-ae56-4e60c2653fa5
            userCondition: null
          -
            dateAdded: '2025-02-27T04:41:37+00:00'
            elementCondition: null
            fieldUid: 61317d04-b4b5-4b2f-ad77-e1d87029c361 # Legacy URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6cfd8793-0399-462a-946c-8d06895f08a6
            userCondition: null
            warning: null
            width: 100
        name: 'Sharing & SEO'
        uid: 532fbb8a-9b44-45b6-b47d-d17f2d7d2d48
        userCondition: null
handle: resource
hasTitleField: true
icon: book
name: Resource
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
