color: blue
description: null
fieldLayouts:
  e39f7b0c-a718-43da-b0d2-02807f5cb593:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-21T04:21:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b5e4cb0a-59d9-4e16-bfc3-408104521a11 # URL
            handle: hyperlink
            instructions: null
            label: __blank__
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b09d46ac-4a55-4a3d-9a66-de7b1abbd069
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 32f0cf7d-280d-4c14-9edb-cd1d256ecafe
        userCondition: null
handle: socialWhatsapp
hasTitleField: false
icon: whatsapp
name: 'Social: WhatsApp'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
