color: blue
fieldLayouts:
  5b831f03-21ea-4889-86fe-606af00fd1a4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-21T04:19:26+00:00'
            elementCondition: null
            fieldUid: b5e4cb0a-59d9-4e16-bfc3-408104521a11 # URL
            handle: hyperlink
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8866445-6ab0-4c8a-8061-fcf4d897848c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7c256bca-0f51-4081-a161-cb60eadd4c44
        userCondition: null
handle: socialBluesky
hasTitleField: false
icon: globe
name: BlueSky
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
