color: null
fieldLayouts:
  6c2b842a-a2ff-4668-9e41-ea3c489351ba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-18T04:00:53+00:00'
            elementCondition: null
            fieldUid: afc7f0bc-1b97-4841-a1d2-5b0385a7ca35 # Plain Text
            handle: quote
            includeInCards: false
            instructions: null
            label: Quote
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dce8f44-1b50-46a9-b253-f6cad99f3dd7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-18T04:00:53+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\RelationalFieldConditionRule
                  fieldUid: 96f5233c-d76d-4f31-9f8d-6de2dfc22373 # Author
                  layoutElementUid: f8b44222-f6d4-490b-addb-5d2948a524b9
                  operator: empty
                  uid: d351d028-0f19-46b5-9147-6af7893966a5
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 840acb32-6694-40d0-9384-60a0220c1de0 # Label
            handle: testimonialAuthor
            includeInCards: false
            instructions: null
            label: Author
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36b64021-f6b3-4968-ac0a-08bef7157ff9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-18T04:00:53+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\TextFieldConditionRule
                  fieldUid: 840acb32-6694-40d0-9384-60a0220c1de0 # Label
                  layoutElementUid: 36b64021-f6b3-4968-ac0a-08bef7157ff9
                  operator: notempty
                  uid: 21f620dc-3a85-4105-a090-9301e13ebaef
                  value: ''
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 840acb32-6694-40d0-9384-60a0220c1de0 # Label
            handle: designation
            includeInCards: false
            instructions: null
            label: Designation
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f764279c-eb06-41ef-a694-a0aa1029a95d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-18T04:07:28+00:00'
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\TextFieldConditionRule
                  fieldUid: 840acb32-6694-40d0-9384-60a0220c1de0 # Label
                  layoutElementUid: 36b64021-f6b3-4968-ac0a-08bef7157ff9
                  operator: empty
                  uid: 3946a772-47f0-4a33-a4be-42f8e8406cb3
                  value: ''
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 96f5233c-d76d-4f31-9f8d-6de2dfc22373 # Author
            handle: existingAuthor
            includeInCards: false
            instructions: null
            label: 'Choose Exiting Person'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8b44222-f6d4-490b-addb-5d2948a524b9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a9705d4-3b74-4c99-8b89-a2e7f2a5d14b
        userCondition: null
handle: testimonial
hasTitleField: false
icon: comment
name: Testimonial
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
