css: ".ck.ck-content h3 { font-size: x-large; }\r\n.ck.ck-content h4 { font-size: large; }"
headingLevels: false
name: 'Builder (Nested)'
options:
  heading:
    options:
      -
        class: ck-heading_paragraph
        model: paragraph
        title: Paragraph
      -
        class: ck-heading_heading3
        model: heading3
        title: Heading
        view: h4
  link:
    decorators:
      openInNewTab:
        attributes:
          target: _blank
        label: 'Open in a new tab'
        mode: manual
    defaultProtocol: 'http://'
  list:
    properties:
      reversed: false
      startIndex: true
      styles: false
toolbar:
  - createEntry
  - heading
  - blockQuote
  - '|'
  - bold
  - italic
  - link
  - bulletedList
  - numberedList
