columnSuffix: null
handle: authorOptions
instructions: null
name: 'Author Type'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Existing Person'
        -
          - value
          - existingPerson
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Custom Person'
        -
          - value
          - customPerson
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
