columnSuffix: null
handle: authors
instructions: null
name: Authors
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add authors'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:08b4a047-a20d-4d56-81b0-32b599c4fb41' # People
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
