columnSuffix: null
handle: body
instructions: null
name: Body
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: e03f52b8-38a8-493c-b27a-3c61c5532f18 # Builder
  createButtonLabel: 'Insert block'
  defaultTransform: null
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 6caf0d7f-9b74-4ae4-b0dd-458633bd94d1 # Image
    -
      __assoc__:
        -
          - uid
          - 64ee8bca-fd54-4c78-853c-aaf37e0bb8c0 # Gallery
    -
      __assoc__:
        -
          - uid
          - 0dcf57f2-a803-4b2e-8235-bc0870989f38 # Media Embed
    -
      __assoc__:
        -
          - uid
          - 21177498-20b3-426a-bf81-df7eeec48389 # Block: Button
        -
          - name
          - Button
    -
      __assoc__:
        -
          - uid
          - fa35f4cd-b237-4493-8c4e-4e25855164ff # Block: Rich Text Collapse
        -
          - name
          - Collapse
  expandEntryButtons: false
  fullGraphqlData: false
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
