columnSuffix: null
handle: body_nested
instructions: null
name: 'Body (Nested)'
searchable: true
settings:
  advancedLinkFields: null
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  css: '.ck.ck-content h4 { font-size: large; }'
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 6caf0d7f-9b74-4ae4-b0dd-458633bd94d1 # Image
        -
          - expanded
          - false
    -
      __assoc__:
        -
          - uid
          - 64ee8bca-fd54-4c78-853c-aaf37e0bb8c0 # Gallery
        -
          - expanded
          - false
    -
      __assoc__:
        -
          - uid
          - 0dcf57f2-a803-4b2e-8235-bc0870989f38 # Media Embed
        -
          - expanded
          - false
    -
      __assoc__:
        -
          - uid
          - 21177498-20b3-426a-bf81-df7eeec48389 # Block: Button
        -
          - name
          - Button
        -
          - expanded
          - false
  fullGraphqlData: true
  headingLevels:
    - '2'
  imageEntryTypeUid: 64ee8bca-fd54-4c78-853c-aaf37e0bb8c0 # Gallery
  imageFieldUid: a193356a-af38-4076-b3ad-bdde75709e4a
  imageMode: img
  js: null
  jsFile: null
  options:
    __assoc__:
      -
        - heading
        -
          __assoc__:
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - class
                      - ck-heading_paragraph
                    -
                      - model
                      - paragraph
                    -
                      - title
                      - Paragraph
                -
                  __assoc__:
                    -
                      - class
                      - ck-heading_heading2
                    -
                      - model
                      - heading2
                    -
                      - title
                      - Subheading
                    -
                      - view
                      - h4
      -
        - link
        -
          __assoc__:
            -
              - decorators
              -
                __assoc__:
                  -
                    - openInNewTab
                    -
                      __assoc__:
                        -
                          - attributes
                          -
                            __assoc__:
                              -
                                - target
                                - _blank
                        -
                          - label
                          - 'Open in a new tab'
                        -
                          - mode
                          - manual
            -
              - defaultProtocol
              - 'http://'
      -
        - list
        -
          __assoc__:
            -
              - properties
              -
                __assoc__:
                  -
                    - reversed
                    - false
                  -
                    - startIndex
                    - true
                  -
                    - styles
                    - false
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - createEntry
    - heading
    - blockQuote
    - '|'
    - bold
    - italic
    - link
    - bulletedList
    - numberedList
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
