columnSuffix: null
handle: callToAction
instructions: null
name: 'Call To Action'
searchable: true
settings:
  createButtonLabel: 'Add link'
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 1e38f7ad-622b-4515-9e15-d3998d50cfb6 # Block: Call To Action
        -
          - name
          - 'Call To Action'
  includeTableView: false
  maxEntries: 1
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
