columnSuffix: null
handle: contentBlocksProgrammes
instructions: '_Programmes Structure_ will automatically shown as the first block. To change the order, add a _Programmes Structure_ block below and move it around.'
name: 'Content Blocks: Programmes'
searchable: true
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - c14871e2-5d6f-434b-823f-597234dc34ef # Block: Programme Structure
        -
          - name
          - 'Programme Structure'
    -
      __assoc__:
        -
          - uid
          - 09d5d648-f5ec-41b7-b39e-4d3c1585936a # Block: Testimonials
        -
          - name
          - Testimonials
    -
      __assoc__:
        -
          - uid
          - b98cf6e6-e5b0-4ec2-9b35-57cfa6114ac1 # Block: People Teasers
        -
          - name
          - People
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
