columnSuffix: null
handle: contentBuilder
instructions: 'Core content will automatically be added after the _Body_ area. To change the order, add a _Core Content_ block and move it around.'
name: 'Content Builder'
searchable: true
settings:
  createButtonLabel: 'Add content block'
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 15a8b3cd-e87e-4daa-aad0-a9f78eabfca7 # Content Builder: Section Core Content
        -
          - name
          - 'Page Specific Content'
    -
      __assoc__:
        -
          - uid
          - 09d5d648-f5ec-41b7-b39e-4d3c1585936a # Content Builder: Testimonials
        -
          - name
          - Testimonials
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
