columnSuffix: null
handle: contactSocialInformation
instructions: null
name: 'Contact & Social Media Information'
searchable: true
settings:
  createButtonLabel: 'Add contact info'
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 1b75b0c0-3003-4fe3-bc8f-478e12906e75 # Contact: Email
        -
          - name
          - Email
    -
      __assoc__:
        -
          - uid
          - 7395f359-de01-4595-b728-81edf64158fc # Phone
    -
      __assoc__:
        -
          - uid
          - aaee4c78-a676-4fb7-b7d5-89c41725efa1 # Contact: Website
        -
          - name
          - Website
    -
      __assoc__:
        -
          - uid
          - 14f7242a-668c-4d66-a588-17cde4b7e598 # Social Media
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
