columnSuffix: null
handle: dateTime
instructions: null
name: 'Date & Time'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 15
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
