columnSuffix: null
handle: departments
instructions: null
name: Departments
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add departments'
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:a71afc7e-315c-4be0-b69b-5c70a7dc85db' # Departments
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
