columnSuffix: null
handle: employmentTypes
instructions: 'Eg: _Full Time_, _Contractual_.'
name: 'Employment Types'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a type'
  showSearchInput: true
  showSiteMenu: true
  source: 'group:7da8d57d-2f04-4b73-a787-e23c441a48f4' # Employment Types
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
