columnSuffix: null
handle: entries
instructions: null
name: Entries
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources:
    - 'section:653ea464-6b43-4bc9-8138-79615323d877' # Blog
    - 'custom:7e0fdfb7-2573-4d33-9aa1-9d6f7877de37'
    - 'section:a71afc7e-315c-4be0-b69b-5c70a7dc85db' # Departments
    - 'section:a976662e-fc19-4f89-ae6b-a5b4db64752b' # Events
    - 'custom:3765d7ff-9a91-48f6-bd36-1008e96248d1'
    - 'custom:bb29a724-9ba6-4bcb-bcaa-928112733af1'
    - 'custom:1aa71832-b8e6-4557-b0d7-6fcea7f324b3'
    - 'section:febb1068-1cf0-4781-8a41-bf420bb95e2f' # Jobs
    - 'section:94e56347-cb09-47d3-a930-1fd9bc2cb026' # News
    - 'section:54bdab3f-b980-46c0-a830-de704b143895' # Offices
    - 'section:e0240263-c706-4560-ad08-6682ee2135f1' # Organisations
    - 'custom:74176ca4-24f3-451c-9878-05473385ae3e'
    - 'section:6b8b6979-d75e-432e-8798-2fc0d53eb8f8' # Pages
    - 'section:3efc7d18-2f42-40d1-beee-b05867f36104' # Programmes
    - 'section:1aa8a857-2e3d-4a1c-a09c-9c180aa2fc53' # Projects
    - 'section:5280da4e-b8fa-4970-9b39-490dd3a96904' # Publications
    - 'custom:8011777f-f2c5-449e-9053-d48b36d995f6'
    - 'section:be130f04-1c51-420d-818e-6d4f5a5960fa' # Resources
    - 'section:7a544871-c8af-4dc8-83ae-dc5001bc8203' # Tenders
    - 'custom:b6b6db60-afda-4442-8e36-6279d2b2387d'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
