columnSuffix: null
handle: eventTypes
instructions: 'Eg: _Exhibitions_, _Screening_.'
name: 'Event Types'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add types'
  showSearchInput: true
  showSiteMenu: true
  source: 'group:8a5099a8-7b2e-4052-b798-5e7d19f38b15' # Event Types
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
