columnSuffix: null
handle: focusAreas
instructions: null
name: 'Focus Areas'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add focus areas'
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: true
  source: 'group:53c65b45-5d94-4867-95c3-6b235eef1853' # Focus Areas
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
