columnSuffix: null
handle: href_url
instructions: null
name: URL
searchable: true
settings:
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
