columnSuffix: null
handle: hyperlinkAssets
instructions: null
name: 'Link (inc. Assets)'
searchable: true
settings:
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              -
                - 'volume:e421ceea-a2f2-459f-88b9-2695f86047bd' # Images
                - 'volume:89c58a76-1da8-4581-84f1-caf2222de75a' # Documents
            -
              - allowedKinds
              - '*'
            -
              - showUnpermittedVolumes
              - ''
            -
              - showUnpermittedFiles
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - '1'
  types:
    - entry
    - url
    - asset
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
