columnSuffix: null
handle: images
instructions: null
name: Images
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:e421ceea-a2f2-459f-88b9-2695f86047bd' # Images
  defaultUploadLocationSubpath: "{% include '_cp/paths/asset' %}"
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: thumbs
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:e421ceea-a2f2-459f-88b9-2695f86047bd' # Images
  restrictedLocationSubpath: null
  selectionLabel: 'Add one or more images'
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:e421ceea-a2f2-459f-88b9-2695f86047bd' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: thumbs
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
