columnSuffix: null
handle: mediaEmbed
instructions: 'Embed external content such as videos, podcasts or social media posts.'
name: 'Media Embed'
searchable: true
settings:
  url: ''
translationKeyFormat: null
translationMethod: none
type: wrav\oembed\fields\OembedField
