columnSuffix: null
handle: opportunityTypes
instructions: 'Eg. _Administrative_, _Logistics_.'
name: 'Opportunity Types'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a type'
  showSearchInput: true
  showSiteMenu: true
  source: 'group:df899104-7d07-489b-954f-20ec40505f31' # Opportunity Types
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
