columnSuffix: null
handle: programmeType
instructions: 'Eg.: _Undergraduate_, _Postgraduate_.'
name: 'Programme Type'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Add a type'
  showCardsInGrid: false
  showSiteMenu: true
  source: 'group:6d709589-8e2f-4fef-9c6f-48f5644fb922' # Disciplines
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
