columnSuffix: null
handle: resourceTypes
instructions: 'Eg: _Development Kit_, _Program_.'
name: 'Resource Types'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add types'
  showSearchInput: true
  showSiteMenu: true
  source: 'group:58e76d43-a465-4c1a-b102-2726a9fc13f5' # Resources Types
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
