columnSuffix: null
handle: simpletext
instructions: null
name: 'Simple Text'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: fd23984e-764a-4004-9834-8efe25601ba5 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
