columnSuffix: null
handle: socialMedia
instructions: null
name: 'Social Media'
searchable: true
settings:
  addRowLabel: 'Add a link'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Social Media'
            -
              - handle
              - socialMedia
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - Bluesky
                    -
                      - value
                      - bluesky
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Facebook
                    -
                      - value
                      - facebook
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Instagram
                    -
                      - value
                      - instagram
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - LinkedIn
                    -
                      - value
                      - linkedin
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Mastodon
                    -
                      - value
                      - mastodon
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - X
                    -
                      - value
                      - x
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Youtube
                    -
                      - value
                      - youtube
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Other
                    -
                      - value
                      - other
                    -
                      - default
                      - true
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - URL
            -
              - handle
              - url
            -
              - width
              - ''
            -
              - type
              - url
  defaults:
    -
      __assoc__:
        -
          - col1
          - other
        -
          - col2
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
