columnSuffix: null
handle: testimonials
instructions: null
name: Testimonials
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add testimonials'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:e39594b6-01d5-4f33-b105-7b111cb3214a' # Testimonials
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
