columnSuffix: null
handle: toggleOff
instructions: null
name: 'Toggle (Default: off)'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
