dateModified: 1734390659
email:
  fromEmail: $CRAFT_FROM_EMAIL
  fromName: $CRAFT_FROM_NAME
  replyToEmail: null
  template: null
  transportSettings:
    host: $CRAFT_SMTP_HOST
    password: $CRAFT_SMTP_PASSWORD
    port: $CRAFT_SMTP_PORT
    useAuthentication: '1'
    username: $CRAFT_SMTP_USER
  transportType: craft\mail\transportadapters\Smtp
fs:
  contentMedia:
    hasUrls: false
    name: 'Private Uploads'
    settings:
      path: '@contentBasePath'
    type: craft\fs\Local
    url: null
  webAssets:
    hasUrls: true
    name: 'Public Static Assets'
    settings:
      path: '@assetBasePath/img/assets'
    type: craft\fs\Local
    url: '@assetBaseUrl/img/assets/'
  webMedia:
    hasUrls: true
    name: 'Public Uploads'
    settings:
      path: '@assetBasePath/media'
    type: craft\fs\Local
    url: '@assetBaseUrl/media/'
  webTransforms:
    hasUrls: true
    name: 'Public Generated Transforms'
    settings:
      path: '@assetBasePath/images/t'
    type: craft\fs\Local
    url: '@assetBaseUrl/images/t'
meta:
  __names__:
    5d68dab3-70f1-4fbc-833e-e504aa7c926d: 'User Photos' # User Photos
    7b8b18a2-8e96-4b93-bfaa-34a1d9fa86e1: Rich # Rich
    08b5b22b-fb98-46ef-8a90-e392edb2244f: 'Rich Text' # Rich Text
    8dddc601-5e96-40bb-b036-520072ba4aa7: Images # Images
    89c58a76-1da8-4581-84f1-caf2222de75a: Documents # Documents
    349b5e6f-3a2a-43f1-a9dd-2373bf4a0a67: 'Share/SEO Description' # Share/SEO Description
    840acb32-6694-40d0-9384-60a0220c1de0: Label # Label
    5661ce90-e09f-4c95-bffe-ffe44c413db3: 'Default Share Image' # Default Share Image
    8447c697-1e38-439d-bfcc-beac5bf1ae31: 'Sharing & SEO' # Sharing & SEO
    69339afc-d4f1-440b-a7ad-7da2ccb77972: Image # Image
    386721be-1ee4-4e3b-b22c-7fb3dfded3ff: 'Simple Text' # Simple Text
    8341919b-4097-4c45-8f3b-97ff673d9ab5: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    a53f5b40-fb8c-4a9d-8c25-dc8e3dfe58d6: Code # Code
    a20788dd-9031-41ba-8145-5f9d17b719ad: Primary # Primary
    afc7f0bc-1b97-4841-a1d2-5b0385a7ca35: 'Plain Text' # Plain Text
    b6ab5147-5d5b-42af-9984-8d4c1b01f63a: 'Static Assets' # Static Assets
    d4720a93-54ad-45de-a939-b668ed8660dc: 'Share/SEO Image' # Share/SEO Image
    da24c053-b31c-4fa8-b113-217845a4ce83: 'Share/SEO Title' # Share/SEO Title
    e421ceea-a2f2-459f-88b9-2695f86047bd: Images # Images
    e5323eec-2cf3-40d3-b122-7df6192a5bdf: 'Form Submissions' # Form Submissions
    fd23984e-764a-4004-9834-8efe25601ba5: Simple # Simple
plugins:
  child-me:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  element-index-defaults:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  environment-label:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  imager-x:
    edition: lite
    enabled: true
    licenseKey: $CRAFT_LICENSE_IMAGER_X
    schemaVersion: 4.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  nocache:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  obfuscator:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  twig-perversion:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: $CRAFT_SITE_NAME
  retryDuration: null
  schemaVersion: 5.5.0.0
  timeZone: Asia/Kolkata
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: '{username}'
  photoVolumeUid: 5d68dab3-70f1-4fbc-833e-e504aa7c926d # User Photos
  require2fa: false
  requireEmailVerification: true
