dateModified: 1734386499
email:
  fromEmail: $CRAFT_FROM_EMAIL
  fromName: $CRAFT_FROM_NAME
  replyToEmail: null
  template: null
  transportSettings:
    host: $CRAFT_SMTP_HOST
    password: $CRAFT_SMTP_PASSWORD
    port: $CRAFT_SMTP_PORT
    useAuthentication: '1'
    username: $CRAFT_SMTP_USER
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    8341919b-4097-4c45-8f3b-97ff673d9ab5: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    a20788dd-9031-41ba-8145-5f9d17b719ad: Primary # Primary
    fd23984e-764a-4004-9834-8efe25601ba5: Simple # Simple
plugins:
  child-me:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  element-index-defaults:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  environment-label:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  imager-x:
    edition: lite
    enabled: true
    licenseKey: $CRAFT_LICENSE_IMAGER_X
    schemaVersion: 4.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  nocache:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  obfuscator:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  twig-perversion:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: $CRAFT_SITE_NAME
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: Asia/Kolkata
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
