fieldLayouts:
  c14c6294-9a5a-4dd1-aab1-d943df3ed0b3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-16T23:14:06+00:00'
            elementCondition: null
            fieldUid: 840acb32-6694-40d0-9384-60a0220c1de0 # Label
            handle: measurementId
            includeInCards: false
            instructions: 'Enter a [GA4 Measurement ID](https://support.google.com/analytics/answer/9304153?hl=en) (formatted as `G-XXXXXXXXXX`) to enable [Google Analytics](https://analytics.google.com/) tracking.'
            label: 'Google Analytics 4 Measurement ID'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 470a6b80-70a0-48dc-854b-4aa3d8e68a03
            userCondition: null
            warning: 'Tracking visitors has a small performance hit on page loading speed.'
            width: 100
        name: Content
        uid: bcba3073-654b-4796-9087-5093e2e96aa9
        userCondition: null
handle: googleAnalytics
name: 'Google Analytics'
sortOrder: 4
