fieldLayouts:
  83bc2f98-29fb-4952-b23b-57282fb67927:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-17T21:31:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a53f5b40-fb8c-4a9d-8c25-dc8e3dfe58d6 # Code
            handle: embedcode
            instructions: null
            label: 'Newsletter Form Embed Code'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a83275a-9c85-41d9-9a91-91f90b0b451b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54091157-9352-491d-b784-9fa51b24e0b5
        userCondition: null
    thumbFieldKey: null
handle: newsletter
name: Newsletter
sortOrder: 4
