fieldLayouts:
  8fe4fcdf-41e6-4f3c-82d4-51ca865256e1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-16T23:10:59+00:00'
            elementCondition: null
            fieldUid: 5661ce90-e09f-4c95-bffe-ffe44c413db3 # Default Share Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36890a3f-ee45-4413-86f1-5ba9addfa3a9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cb56995e-fe58-497c-a15f-1c923488bb3c
        userCondition: null
handle: seo
name: 'Sharing & SEO'
sortOrder: 2
