#
# main.conf (CDN app)
# /etc/nginx-rc/extra.d/<web-app>.location.main.include.conf
# 
# Custom conf for the server {} block
#



# -------
# Headers
# -------

# Enable content from the CDN to be embedded inside the primary domain.
# Disable X-Frame-Options header inside RunCloud first
# [Web App] > Settings > Nginx Config > [ ] Clickjacking Protection
add_header Content-Security-Policy "frame-src 'self' https://$PRIMARY_DOMAIN;";



# ----------------------
# Handle more file types
# ----------------------

location ~* \.(?:json)$ {
  expires 1M;
  access_log off;
  add_header "Access-Control-Allow-Origin" "*";
  add_header Cache-Control "public";
}
