defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9f12d494-ef8f-4777-8ff0-bebc044b1264 # Academic Level
handle: academicLevels
maxAuthors: 1
name: 'Academic Levels'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
