defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c8c8ccd9-ebdc-48dd-bac8-029cb3d04923 # Department
handle: departments
maxAuthors: 1
name: Departments
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _routers/detail.twig
    uriFormat: 'departments/{slug}'
type: channel
