defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 12c6ecb1-eb21-40a2-aca1-217b86047c44 # Event
handle: events
maxAuthors: 1
name: Events
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _routers/detail.twig
    uriFormat: 'events/{slug}'
type: channel
