defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 12c6ecb1-eb21-40a2-aca1-217b86047c44 # Event
handle: events
maxAuthors: 1
minAuthors: 1
name: Events
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
  -
    label: 'Link previews'
    refresh: '1'
    urlFormat: '_preview/all/{canonicalUid}'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _routers/detail.twig
    uriFormat: 'events/{slug}'
type: channel
