defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c8c8ccd9-ebdc-48dd-bac8-029cb3d04923 # Faculty
handle: faculties
maxAuthors: 1
name: Faculties
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _routers/detail.twig
    uriFormat: 'faculties/{slug}'
type: channel
