defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c2bd9b72-0968-4b24-aee2-02048ebf7f8c # Job
handle: jobs
maxAuthors: 1
minAuthors: 1
name: Jobs
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
  -
    label: 'Link previews'
    refresh: '1'
    urlFormat: '_preview/all/{canonicalUid}'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _routers/detail.twig
    uriFormat: 'jobs/{slug}'
type: channel
