defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9eb91e5d-0e36-4e64-9422-f92401aa9500 # Location
handle: locations
maxAuthors: 1
minAuthors: 1
name: Locations
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: f6cf21c5-bd0a-44f5-846d-ecebb189f68e
type: structure
