defaultPlacement: end
enableVersioning: true
entryTypes:
  - a385a4fe-5736-44ee-ab48-d869428d380c # News
handle: news
maxAuthors: 1
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: news/_entry.twig
    uriFormat: 'news/{slug}'
type: channel
