defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a385a4fe-5736-44ee-ab48-d869428d380c # News
handle: news
maxAuthors: 1
minAuthors: 1
name: News
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _routers/detail.twig
    uriFormat: 'news/{slug}'
type: channel
