defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f719c927-90fd-4ace-a58e-ddea5675c7d2 # Office
handle: offices
maxAuthors: 1
name: Offices
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _routers/detail.twig
    uriFormat: 'offices/{slug}'
type: channel
