defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 58d94df4-b6dd-4ff7-9157-3b7d7e24b66d # Organisation
handle: organisations
maxAuthors: 1
name: Organisations
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
