defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a404ee2c-1d0d-4da9-a736-cd565a4d2605 # Page
handle: pages
maxAuthors: 1
minAuthors: 1
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _routers/detail.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: f836a579-5919-4a54-8177-4a5b74c636e4
type: structure
