defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: ad5b3d91-425f-4181-8ded-f9c7c53a6bba # Person
handle: people
maxAuthors: 1
name: People
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _routers/detail.twig
    uriFormat: 'people/{slug}'
type: channel
