defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    name: 'Org Member'
    uid: dd80a6fe-320a-4fb6-889d-17125d275aac # People: Org Member
  -
    name: 'External Contributor'
    uid: 6fd87453-1bda-4bb9-8c8d-4dd36185e75d # People: External Contributor
handle: people
maxAuthors: 1
minAuthors: 1
name: People
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _routers/detail.twig
    uriFormat: "{% include('_cp/urls/people') %}"
type: channel
