defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: dd80a6fe-320a-4fb6-889d-17125d275aac # Org Member
  -
    uid: 6fd87453-1bda-4bb9-8c8d-4dd36185e75d # External Contributor
handle: people
maxAuthors: 1
name: People
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _routers/detail.twig
    uriFormat: 'members/{slug}'
structure:
  maxLevels: 1
  uid: 3760b257-08c1-4c72-b232-18a46eabe54a
type: structure
