defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c4fb7c86-c508-4410-9362-e47f5b604631 # Program
handle: programs
maxAuthors: 1
name: Programs
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _routers/detail.twig
    uriFormat: 'programs/{slug}'
type: channel
