defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7e194f18-cd05-4cd2-bc77-67272aaa31a3 # Testimonial
handle: testimonials
maxAuthors: 1
name: Testimonials
propagationMethod: all
siteSettings:
  8341919b-4097-4c45-8f3b-97ff673d9ab5: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
